[package]
name = "asset-discovery"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = "1.0.37"
serde_json = "1.0.133"
syn = { version = "2.0", features = ["full", "visit"] }
serde = { version = "1.0", features = ["derive"] }
