[package]
name = "threat-modeling"
version = "0.1.0"
edition = "2021"

[dependencies]
langchain-rust = "4.6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.135"
tokio = "1.43.0"
pallet-test-proc-macro = { path = "../pallet-test-proc-macro" }
